#!/usr/bin/env bash
# Argus — one-time Cloudflare Tunnel setup for the Telegram bridge.
#
# This script is NOT part of install-mac.sh's automated flow because
# `cloudflared tunnel login` requires interactive browser-based auth.
# Run this ONCE on the host, then run install-mac.sh which will pick up
# the rendered ~/.cloudflared/config.yml and install the launchd plist.
#
# Requirements:
#   - cloudflared installed on PATH (Phase A's section_brew_packages did this).
#   - A Cloudflare account with a domain/zone you own.
#   - Env: ARGUS_TUNNEL_HOSTNAME — fully-qualified hostname under that zone
#          (e.g. argus-bridge.example.com).
#
# Idempotent — safe to re-run. Existing tunnel/route/config are detected
# and reused; only the missing pieces are created.

set -euo pipefail

TUNNEL_NAME="argus-bridge"
BRIDGE_PORT="${BRIDGE_PORT:-9501}"
CFD_DIR="$HOME/.cloudflared"
CFG_FILE="$CFD_DIR/config.yml"
SECRETS_FILE="$HOME/.argus/secrets.env"

log() { printf '\033[1;34m[argus-cloudflared]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[argus-cloudflared]\033[0m %s\n' "$*" >&2; }
fail() { printf '\033[1;31m[argus-cloudflared]\033[0m %s\n' "$*" >&2; exit 1; }

require_cloudflared() {
  command -v cloudflared >/dev/null 2>&1 || \
    fail "cloudflared not on PATH. Run scripts/install-mac.sh first (it brew-installs cloudflared)."
}

require_hostname() {
  [[ -n "${ARGUS_TUNNEL_HOSTNAME:-}" ]] || fail "ARGUS_TUNNEL_HOSTNAME is required.
Example:
  ARGUS_TUNNEL_HOSTNAME=argus-bridge.example.com bash scripts/install-cloudflared.sh
The hostname must be under a Cloudflare zone you control."
}

# Step 1: cloudflared tunnel login (interactive, one-time)
# A successful login writes ~/.cloudflared/cert.pem. We probe for that file
# rather than re-running login every time.
ensure_login() {
  if [[ -f "$CFD_DIR/cert.pem" ]]; then
    log "cloudflared cert.pem already present — skipping login"
    return
  fi
  log "Running 'cloudflared tunnel login' — a browser window will open."
  log "  Pick the Cloudflare zone matching '$ARGUS_TUNNEL_HOSTNAME'."
  cloudflared tunnel login
  [[ -f "$CFD_DIR/cert.pem" ]] || fail "Login finished but $CFD_DIR/cert.pem was not created."
}

# Step 2: create the named tunnel (idempotent — list+grep first)
ensure_tunnel() {
  if cloudflared tunnel list 2>/dev/null | awk '{print $2}' | grep -qx "$TUNNEL_NAME"; then
    log "Tunnel '$TUNNEL_NAME' already exists — skipping create"
  else
    log "Creating tunnel '$TUNNEL_NAME'"
    cloudflared tunnel create "$TUNNEL_NAME"
  fi
}

# Step 3: extract tunnel UUID from the credentials JSON file (~/.cloudflared/<uuid>.json).
# `cloudflared tunnel list` also reports it, but parsing the formatted table is brittle.
# The credentials file's basename IS the UUID. Multiple tunnels could exist on this host;
# we resolve the UUID for OUR tunnel by pairing it with the name from `tunnel list`.
resolve_tunnel_id() {
  local id
  id="$(cloudflared tunnel list 2>/dev/null | awk -v name="$TUNNEL_NAME" '$2==name {print $1}' | head -n1)"
  [[ -n "$id" ]] || fail "Could not resolve tunnel ID for '$TUNNEL_NAME'."
  printf '%s\n' "$id"
}

# Step 4: route the public hostname to this tunnel.
# Cloudflare's API treats the route-add as upsert; running it twice on the same
# (tunnel, hostname) is a no-op. We still log a clear "ensure" message.
ensure_route() {
  log "Ensuring DNS route: $ARGUS_TUNNEL_HOSTNAME -> tunnel '$TUNNEL_NAME'"
  cloudflared tunnel route dns "$TUNNEL_NAME" "$ARGUS_TUNNEL_HOSTNAME" || \
    warn "route dns returned non-zero — this is OK if the route was already in place."
}

# Step 5: render ~/.cloudflared/config.yml mapping the public hostname
# to the local bridge. Atomic write (tmp + chmod + mv) so a power loss
# during write can't truncate the config and brick the tunnel on next start.
render_config() {
  local tunnel_id="$1"
  mkdir -p "$CFD_DIR"
  local tmp="$CFG_FILE.tmp.$$"
  cat > "$tmp" <<EOF
# Argus — generated by scripts/install-cloudflared.sh — do not edit by hand.
# Re-run that script to regenerate. Real edits should go into the script's
# heredoc.
tunnel: $tunnel_id
credentials-file: $CFD_DIR/$tunnel_id.json

ingress:
  - hostname: $ARGUS_TUNNEL_HOSTNAME
    service: http://127.0.0.1:$BRIDGE_PORT
  - service: http_status:404
EOF
  chmod 600 "$tmp"
  mv "$tmp" "$CFG_FILE"
  log "Wrote $CFG_FILE"
}

# Step 6: persist tunnel UUID to ~/.argus/secrets.env so the launchd plist
# (and any future tooling) can reference it without re-parsing the YAML.
# Idempotent: grep before append; replace if a stale value is present.
persist_tunnel_id() {
  local tunnel_id="$1"
  mkdir -p "$(dirname "$SECRETS_FILE")"
  if [[ ! -f "$SECRETS_FILE" ]]; then
    fail "Missing $SECRETS_FILE — complete Phase A's Task 6 (Discord webhook) first."
  fi
  if grep -q '^ARGUS_TUNNEL_ID=' "$SECRETS_FILE"; then
    local current
    current="$(grep '^ARGUS_TUNNEL_ID=' "$SECRETS_FILE" | head -n1 | sed 's/^ARGUS_TUNNEL_ID=//; s/^"//; s/"$//')"
    if [[ "$current" == "$tunnel_id" ]]; then
      log "ARGUS_TUNNEL_ID already set in $SECRETS_FILE"
      return
    fi
    log "Updating ARGUS_TUNNEL_ID in $SECRETS_FILE (was: $current)"
    local tmp="$SECRETS_FILE.tmp.$$"
    sed "s|^ARGUS_TUNNEL_ID=.*|ARGUS_TUNNEL_ID=\"$tunnel_id\"|" "$SECRETS_FILE" > "$tmp"
    chmod 600 "$tmp"
    mv "$tmp" "$SECRETS_FILE"
  else
    log "Appending ARGUS_TUNNEL_ID to $SECRETS_FILE"
    printf '\n# Argus — Cloudflare Tunnel UUID (added by install-cloudflared.sh)\nARGUS_TUNNEL_ID="%s"\n' \
      "$tunnel_id" >> "$SECRETS_FILE"
  fi
  chmod 600 "$SECRETS_FILE"
}

print_next_steps() {
  cat <<EOF

==> Next steps:

1. Run scripts/install-mac.sh to install the cloudflared launchd plist
   (section_cloudflared will pick up $CFG_FILE automatically).

2. Once cloudflared and the bridge are both running, register the
   Telegram webhook (operator only — the bot token never leaves your host):

     # shellcheck disable=SC2154
     source ~/.argus/secrets.env
     curl -fsS -X POST "https://api.telegram.org/bot\${TELEGRAM_BOT_TOKEN}/setWebhook" \\
       -d "url=https://$ARGUS_TUNNEL_HOSTNAME/telegram" \\
       -d "secret_token=\${TELEGRAM_WEBHOOK_SECRET}"

3. Verify the webhook is registered:

     curl -fsS "https://api.telegram.org/bot\${TELEGRAM_BOT_TOKEN}/getWebhookInfo"

   The 'url' field should match https://$ARGUS_TUNNEL_HOSTNAME/telegram and
   'last_error_message' should be empty.
EOF
}

main() {
  require_cloudflared
  require_hostname
  ensure_login
  ensure_tunnel
  ensure_route
  local tunnel_id
  tunnel_id="$(resolve_tunnel_id)"
  log "Tunnel ID: $tunnel_id"
  render_config "$tunnel_id"
  persist_tunnel_id "$tunnel_id"
  print_next_steps
}

main "$@"
